version: 2
updates:

  # Docker
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25

  # Python
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25
    groups:
      python-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25
