version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the FastAPI server
  cdm_task_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongodb
    environment:
      - KBCOLL_KBASE_AUTH2_URL=https://ci.kbase.us/services/auth
      - KBCOLL_KBASE_AUTH2_ADMIN_ROLES=CDM_TASK_SERVICE_ADMIN

# TODO MINIO add minio

  mongodb:
    image: "mongo:7.0.14"
    ports:
      - "27017:27017"
