version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the FastAPI server
  cdm_task_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    #extra_hosts:
      # TODO DOCKERUPGRADE after upgrading docker switch from host mode
      # See https://stackoverflow.com/a/43541732/643675
      #- "host.docker.internal:host-gateway"
    network_mode: host
    depends_on:
      - mongodb
      - minio
    environment:
      - KBCTS_KBASE_AUTH2_URL=https://ci.kbase.us/services/auth
      - KBCTS_KBASE_AUTH2_ADMIN_ROLES=CDM_TASK_SERVICE_ADMIN
      - KBCTS_KBASE_STAFF_ROLE=KBASE_STAFF
      - KBCTS_HAS_NERSC_ACCOUNT_ROLE=HAS_NERSC_ACCOUNT
      - KBCTS_SFAPI_CRED_PATH=/creds/sfapi_creds
      - KBCTS_SFAPI_USER=cdm_ts
      - KBCTS_NERSC_REMOTE_CODE_DIR=/global/cfs/cdirs/kbase/cdm_task_service
      - KBCTS_NERSC_FILE_GROUP=kbase
      # Don't commit your token to github please
      - KBCTS_JAWS_TOKEN=tokengoeshere
      - KBCTS_JAWS_GROUP=kbase
      # TODO DOCKERUPGRADE after upgrading docker switch to host.docker.internal
      - KBCTS_S3_URL=http://localhost:9002
      #- KBCTS_S3_URL=http://host.docker.internal:9002
      # local Minio, only useful if not running jobs on NERSC
      #- KBCTS_S3_URL=http://minio:9000
      - KBCTS_S3_EXTERNAL_URL=https://ci.berkeley.kbase.us:9000
      - KBCTS_VERIFY_S3_EXTERNAL_URL=false
      - KBCTS_S3_ACCESS_KEY=miniouser
      - KBCTS_S3_ACCESS_SECRET=miniopassword
      - KBCTS_S3_ALLOW_INSECURE=true
      # TODO DOCKERUPGRADE switch back when host mode no longer needed
      - KBCTS_MONGO_HOST=mongodb://localhost:27017
      #- KBCTS_MONGO_HOST=mongodb://mongodb:27017
      - KBCTS_MONGO_DB=cdmtaskservice
      # TODO MONGOAUTH need to add a user to the cmdtaskservice db before this works out
      #                of the box.
      #                The env vars in mongodb below only create a user in admin and only if
      #                the data directory is empty.
      # - KBCTS_MONGO_USER=root
      # - KBCTS_MONGO_PWD=secret
      - KBCTS_MONGO_RETRYWRITES=false
      - KBCTS_SERVICE_ROOT_URL=https://ci.kbase.us/services/cts
    volumes:
      - ./tmp_creds:/creds

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - 9000:9000
      - 9001:9001
    command: 'server /data --console-address ":9001"'

  mongodb:
    image: mongo:7.0.14
    ports:
      - 27017:27017
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=secret
