version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the FastAPI server
  cdm_task_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongodb
      - minio
    environment:
      - KBCTS_KBASE_AUTH2_URL=https://ci.kbase.us/services/auth
      - KBCTS_KBASE_AUTH2_ADMIN_ROLES=CDM_TASK_SERVICE_ADMIN
      - KBCTS_KBASE_STAFF_ROLE=KBASE_STAFF
      - KBCTS_HAS_NERSC_ACCOUNT_ROLE=HAS_NERSC_ACCOUNT
      - KBCTS_SFAPI_CRED_PATH=/creds/sfapi_creds
      - KBCTS_SFAPI_USER=cdm_ts
      - KBCTS_S3_URL=http://minio:9000
      - KBCTS_S3_ACCESS_KEY=miniouser
      - KBCTS_S3_ACCESS_SECRET=miniopassword
    volumes:
      - ./tmp_creds:/creds

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"
      - "9001:9001"
    command: 'server /data --console-address ":9001"'

  mongodb:
    image: "mongo:7.0.14"
    ports:
      - "27017:27017"
