---
name: Run Trivy Scans

on:
  pr:

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t kbase/trivy:scan . 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "kbase/trivy:scan"
          format: "sarif"
          output: "trivy-results.sarif"
          timeout: "20m"
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
